# Generated by Django 4.1.13 on 2024-04-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
