# Generated by Django 4.1.13 on 2024-04-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_product_user_delete_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headling', models.CharField(max_length=255)),
                ('in_completed', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
